# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: false
font: ''
font_size: L

# SEO

site_type: FundingScheme
local_business_type: ''
org_name: 'goJewish.eu'
description: 'Support the Jewish Community today! Financial donations of any size help fund our programs.'
twitter: ''

# Contact (edit or remove options as required)

email: philantropy@jewish.ee
phone: '+3725555920'
address:
  street: Karu 16
  city: Tallinn
  region: Harjumaa
  postcode: '10120'
  country: Estonia
  country_code: EE
coordinates:
  latitude: '59.4387207'
  longitude: '24.7645043'
#directions: Enter Building 1 and take the stairs to Office 200 on Floor 2
#office_hours:
#  - ''
appointment_url: ''
contact_links:
# - icon: twitter
#   icon_pack: fab
#   name: Twitter
#   link: 'https://twitter.com/JewishGo'
#  - icon: skype
#    icon_pack: fab
#    name: Skype Me
#    link: 'skype:echo123?call'
#  - icon: keybase
#    icon_pack: fab
#    name: Chat on Keybase
#    link: 'https://keybase.io/go_jewish'
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: '2 Jan 2006'
time_format: '15:04'
address_format: de

# Site features

highlight: false
highlight_languages:
  - r
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: false
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: ['custom']
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'UA-191476840-1'
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
  netlify_cms: false
icon:
  pack:
    ai: true
